# Generated by Django 5.0.1 on 2024-02-08 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatre_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('row', 'seat', 'performance')},
        ),
    ]
